(define (pos value)
  (cond
    ((eq? value -1 ) (+ value 1) )
    (else (display "Enter a value: ") (+ (pos(read)) value))
  )
)

(define (roundoff number decimalplace)
  (let ((power (expt 10 decimalplace)))
    (/ (round (* power number)) power))
)

(define (main)
  (newline)
  (display "Welcome to the program!")
  (newline)
  (define subtotal (pos 0))
  (display "Subtotal: $")
  (display (roundoff subtotal 2))
  (newline)
  (display "Tax: $")
  (display (roundoff (* subtotal .06) 2))
  (newline)
  (display "Total: $")
  (display (roundoff (+ subtotal (* subtotal .06)) 2))
  (+ 0 0)
)


(main)
